name: 01 - Criando Workflow
on:
  push:
    branches: 'main'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir o evento
        run: echo "Workflow disparado por ${{ github.event_name }}"